### ISSUE TITLE
Repeatable string editor failing

### ISSUE THREAD

**Issue by nikcio** [enterspeedhq/enterspeed-source-umbraco-cms#145]
The implementation of the repeatable string editor cases failures in Umbraco 13. It can be fixed pretty easily with the change below:

https://github.com/enterspeedhq/enterspeed-source-umbraco-cms/blob/8bb0383ca5208f29f7c5b292e8c0bf785d258f0c/src/Enterspeed.Source.UmbracoCms/Services/DataProperties/DefaultConverters/DefaultRepeatableTextStringPropertyValueConverter.cs#L18C43-L18C51

```csharp
IEnumerable<string> items = property.GetValue<IEnumerable<string>>(culture);
```

The error: 
```
Unable to cast object of type 'System.Linq.EmptyPartition`1[System.String]' to type 'System.String[]'.
```

**Comment by jesperweber** [comment]
Hi @nikcio,

Thank you for reporting 😀

Initially I'm not able to reproduce the error. Do you have any special conditions in your setup that I might need to setup as well maybe?

I have tested with Umbraco 13.1.0 and Enterspeed package 4.2.0

![image](https://github.com/enterspeedhq/enterspeed-source-umbraco-cms/assets/2575817/62fce30c-bb0b-48ec-b667-adc6caacb9c4)

![image](https://github.com/enterspeedhq/enterspeed-source-umbraco-cms/assets/2575817/d230a3b1-abab-4703-977e-46a6b8f74dbb)

![image](https://github.com/enterspeedhq/enterspeed-source-umbraco-cms/assets/2575817/5dd284eb-0b34-45b2-b411-9dacf34f2815)

**Comment by nikcio** [comment]
I got the error when i didn't fill anything in the editor while creating the content. 
Also the editor was placed inside a block grid, block

**Comment by jesperweber** [comment]
Thanks, I could reproduces the error when the list was empty, either in a block or on the page it self and your suggestion fixed the issue.

Thank you again for reporting this and for the fix 💪

A new release 4.2.1 is now available on NuGet: https://www.nuget.org/packages/Enterspeed.Source.UmbracoCms/4.2.1
