### ISSUE TITLE
Macros and RTE fields error

### ISSUE THREAD

**Issue by dennispedersenmedia** [enterspeedhq/enterspeed-source-umbraco-cms#54]
I'm gonna start out by saying that this is the first time im trying to run a content seed from umbraco to enterspeed - so bare with me if there's something I've missed!

But,
When trying to seed data it looks like i'm getting errors in RTE fields where I have macros.

![image](https://user-images.githubusercontent.com/10733511/188862992-f28034d2-64d1-4342-aef5-e120f570bfbf.png)

`Exception
Failed creating entity (1295/en-us). Message: The Umbraco.Web.Macros.PartialViewMacroEngine cannot execute with a null HttpContext.Current reference.. StackTrace: ved Umbraco.Web.Macros.PartialViewMacroEngine.<.ctor>b__2_0() i D:\a\1\s\src\Umbraco.Web\Macros\PartialViewMacroEngine.cs:linje 26 ved Umbraco.Web.Macros.PartialViewMacroEngine.Execute(MacroModel macro, IPublishedContent content) i D:\a\1\s\src\Umbraco.Web\Macros\PartialViewMacroEngine.cs:linje 71 ved Umbraco.Web.Macros.MacroRenderer.<>c__DisplayClass17_0.<ExecuteMacroOfType>b__0() i D:\a\1\s\src\Umbraco.Web\Macros\MacroRenderer.cs:linje 342 ved Umbraco.Web.Macros.MacroRenderer.ExecuteProfileMacroWithErrorWrapper(MacroModel macro, String msgIn, Func`1 getMacroContent, Func`1 msgErr) i D:\a\1\s\src\Umbraco.Web\Macros\MacroRenderer.cs:linje 313 ved Umbraco.Web.Macros.MacroRenderer.ExecuteMacroWithErrorWrapper(MacroModel macro, String msgIn, String msgOut, Func`1 getMacroContent, Func`1 msgErr) i D:\a\1\s\src\Umbraco.Web\Macros\MacroRenderer.cs:linje 272 ved Umbraco.Web.Macros.MacroRenderer.ExecuteMacroOfType(MacroModel model, IPublishedContent content) i D:\a\1\s\src\Umbraco.Web\Macros\MacroRenderer.cs:linje 339 ved Umbraco.Web.Macros.MacroRenderer.Render(MacroModel macro, IPublishedContent content, IDictionary pageElements) i D:\a\1\s\src\Umbraco.Web\Macros\MacroRenderer.cs:linje 245 ved Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.<>c__DisplayClass7_0.<RenderRteMacros>b__1(String macroAlias, Dictionary`2 macroAttributes) i D:\a\1\s\src\Umbraco.Web\PropertyEditors\ValueConverters\RteMacroRenderingValueConverter.cs:linje 64 ved Umbraco.Web.Macros.MacroTagParser.ParseMacros(String text, Action`1 textFoundCallback, Action`2 macroFoundCallback) i D:\a\1\s\src\Umbraco.Web\Macros\MacroTagParser.cs:linje 196 ved Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.RenderRteMacros(String source, Boolean preview) i D:\a\1\s\src\Umbraco.Web\PropertyEditors\ValueConverters\RteMacroRenderingValueConverter.cs:linje 70 ved Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.Convert(Object source, Boolean preview) i D:\a\1\s\src\Umbraco.Web\PropertyEditors\ValueConverters\RteMacroRenderingValueConverter.cs:linje 96 ved Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel, Object inter, Boolean preview) i D:\a\1\s\src\Umbraco.Web\PropertyEditors\ValueConverters\RteMacroRenderingValueConverter.cs:linje 78 ved Umbraco.Core.Models.PublishedContent.PublishedPropertyType.ConvertInterToObject(IPublishedElement owner, PropertyCacheLevel referenceCacheLevel, Object inter, Boolean preview) i D:\a\1\s\src\Umbraco.Core\Models\PublishedContent\PublishedPropertyType.cs:linje 221 ved Umbraco.Web.PublishedCache.NuCache.Property.GetValue(String culture, String segment) i D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\Property.cs:linje 211 ved Enterspeed.Source.UmbracoCms.V8.Extensions.PropertyExtensions.GetValue[T](IPublishedProperty property, String culture) ved Enterspeed.Source.UmbracoCms.V8.Services.DataProperties.DefaultConverters.DefaultRichTextEditorPropertyValueConverter.Convert(IPublishedProperty property, String culture) ved Enterspeed.Source.UmbracoCms.V8.Services.EnterspeedPropertyService.ConvertProperties(IEnumerable`1 properties, String culture) ved Enterspeed.Source.UmbracoCms.V8.Services.EnterspeedPropertyService.GetProperties(IPublishedContent content, String culture) ved Enterspeed.Source.UmbracoCms.V8.Handlers.EnterspeedContentPublishJobHandler.CreateUmbracoContentEntity(IPublishedContent content, EnterspeedJob job)`

How to replicate:
1. Create content page with RTE field
2. Insert macro to RTE page
3. Try to seed this page to enterspeed

**Comment by emilras** [comment]
@dennispedersenmedia Thanks for reporting this. 

What version of Umbraco are you using and what is the version of the integration package?

**Comment by dennispedersenmedia** [comment]
hey @emilras 
using Umbraco 8.18.2 and newest version of integration package.
"Enterspeed.Source.UmbracoCms.V8" version="0.15.0"
"Enterspeed.Source.Sdk" version="0.7.1"

**Comment by emilras** [comment]
Discussed on a other channel.
