### ISSUE TITLE
Media File can't contains word src

### ISSUE THREAD

**Issue by bielu** [enterspeedhq/enterspeed-source-umbraco-cms#78]
Based on this line, word src, make https://github.com/enterspeedhq/enterspeed-source-umbraco-cms/blob/639da4d41d7d8abd5729a6e200aedf290994ffdc/src/Enterspeed.Source.UmbracoCms.V9/Extensions/MediaExtensions.cs#L15 that any object containting this word will be parsed and potentially throw exception if it is not crop image object :)
Example name: code-src02.svg :)

**Comment by MHove89** [comment]
This has been fixed. Closing. 
@bielu
